trigger: none
pool: Jan25
steps:
- task: TerraformInstaller@1
  displayName: install
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'NewSConnect'
    backendAzureRmStorageAccountName: 'ankitsg'
    backendAzureRmContainerName: 'statefile'
    backendAzureRmKey: 'p2.terraform.tfstate'